### ISSUE TITLE
{0.9.10HotFix} akashic cfg

### ISSUE THREAD

**Issue by nuclear200** [Zulu-s-Modpacks/Stacia-2-Expert#11]
-cannot put  thinker's guidebooks in the akashic tome (with the exception of the thinker's encyclopedia) {which might be intended behavior}. 
-cannot put astrodux (aka ad astra guidebook) inside akashic tome.
And while i'm on the topic i'd suggest to blacklist the blueskies guidebook because if you open it while in the akashic tome, the tome gets deleted with all its other contents.

**Comment by Zulussuu** [comment]
Fixed
