### ISSUE TITLE
{0.9.10Hotfix} occultism miner mining ... barriers?

### ISSUE THREAD

**Issue by nuclear200** [Zulu-s-Modpacks/Stacia-2-Expert#13]
didn't happen for a double chest worth of mining in 0.9.8, now it got me some barrier blocks XD
![Screenshot 2024-04-17 110458](https://github.com/Zulu-s-Modpacks/Stacia-2-Expert/assets/12127335/919d265a-9b55-4557-a5fd-7ddb23d2ab4d)

**Comment by Zulussuu** [comment]
fixed
