### ISSUE TITLE
{0.9.10Hotfix} slimesteel recipes unbalance and fixes

### ISSUE THREAD

**Issue by nuclear200** [Zulu-s-Modpacks/Stacia-2-Expert#16]
there are a couple of slimesteel recipes that are easier and provide better crafting results:
with the mechanical mixer, recipe from create crafts and additions (1 iron, 1 skyslime, 1 tconstruct:seared_blocks => 2 slimesteel ingots)
with the induction smelter (1 iron, 1 skyslime, 1 seared brick => 2 slimesteel ingots)

and also the arc furnace recipe has not been updated to use the correct skyslime instead of the blue slime ball

**Comment by Zulussuu** [comment]
I fixed it. The problems will be resolved in the next version.
