### ISSUE TITLE
{0.9.10Hotfix} Duplication glitch due to tinker's new amount of fluid per ingot

### ISSUE THREAD

**Issue by nuclear200** [Zulu-s-Modpacks/Stacia-2-Expert#17]
it is possible to create an automated duplication farm for steel and electrum reeeeally early on, with a create mechanical mixer and tinker's smeltery following these steps:
-melt a steel ingot with a create mechanical mixer (144mb molten steel)
-move it to a smeltery
-cast the ingot with the smeltery (-90mb, surplus of 54mb per ingot)
-melt the ingot again in the mechanical mixer

This is caused by the custom recipe for molten steel that creates 144mb instead of the 90 tinker's is working with now.
when this gets fixed remember to patch also the fluid requirements for:
-hydraulic engine
-simple machine frame

**Comment by Zulussuu** [comment]
fixed
