### ISSUE TITLE
[enhancement/fix] occultism miner

### ISSUE THREAD

**Issue by nuclear200** [Zulu-s-Modpacks/Stacia-2-Expert#20]
remove occultism:miner/ores/cobalt_ore
add tconstruct:cobalt_ore to occultism:miners/ores
add kubejs:arcane_ore to occultism:miners/ores

by removing and adding back cobalt as tcon instead of the default, issue #13 <del>might</del> gets fixed

**Comment by Zulussuu** [comment]
done. i hope it works
