### ISSUE TITLE
cannot pulverize aluminium in create crusher/mill

### ISSUE THREAD

**Issue by nuclear200** [Zulu-s-Modpacks/Stacia-2-Expert#24]

**Comment by Zulussuu** [comment]
![image](https://github.com/Zulu-s-Modpacks/Stacia-2-Expert/assets/160519073/0f25cdae-0b92-4495-b759-ca2f91a437c7)
![image](https://github.com/Zulu-s-Modpacks/Stacia-2-Expert/assets/160519073/958c4775-779e-4732-88a1-4319f7f787c1)

**Comment by nuclear200** [comment]
nvm, just jei not showing it on client side on my end, but the recipe works
