### ISSUE TITLE
[0.9.11] Slimesteel ingot craft does not work

### ISSUE THREAD

**Issue by Willox17** [Zulu-s-Modpacks/Stacia-2-Expert#28]
The craft of slimesteel ingot does not work in induction smelter and there's no other recipe in JEI.

![2024-05-03_00 29 39](https://github.com/Zulu-s-Modpacks/Stacia-2-Expert/assets/168785991/957af524-2179-4e8d-8929-d9f2da449fbc)

**Comment by Zulussuu** [comment]
fixed in 0.9.12
