### ISSUE TITLE
Garden Cloche Bug/problem

### ISSUE THREAD

**Issue by caeldorii** [Zulu-s-Modpacks/Stacia-2-Expert#32]
Hello!

Is it intended that the garden cloches are not working with e.g. uranium seeds, fluorite seeds etc.?
In the Stacia Expert pack it worked. 
Greetings

**Comment by Zulussuu** [comment]
Yes it is intended.
Botany Pots Tiers mod is in the modpack. You can use them instead of Garden cloche.
