### ISSUE TITLE
Conflicting Roller Recipe 

### ISSUE THREAD

**Issue by lilgamerhelle** [Zulu-s-Modpacks/Stacia-2-Expert#33]
With the change to the 2fancy kube file we now have two recipes for electrum ingots into the roller

event.remove({ id: 'createaddition:rolling/electrum_plate' }) */
event.custom({"type":"createaddition:rolling","input": {"item": "thermal:electrum_ingot"},"result": {"item": "immersiveengineering:wire_electrum","count": 2}}) */
this change does not remove the electrum ingot into the create rolling machine for rods

I do not think this is intentional as this is the only ingot that behaves this way

**Comment by Zulussuu** [comment]
Will be fixed in 1.0.4
