### ISSUE TITLE
Player Reporting Pause Menu

### ISSUE THREAD

**Issue by Cigwatch** [Zulu-s-Modpacks/Stacia-2-Expert#4]
Player Reporting button is misplaced in the pause menu when you open to LAN in singleplayer.
![image](https://github.com/Zulu-s-Modpacks/Stacia-2-Expert/assets/163697281/1516d5f0-1353-45a2-a777-e719278474af)

**Comment by Zulussuu** [comment]
Thank you, it will be fixed in version 0.9.10
