### ISSUE TITLE
{0.9.10Hotfix} [Infrastructure Dupe BUG] with Immersive Petroleum (likely all multiblocks from IP affected)

### ISSUE THREAD

**Issue by nuclear200** [Zulu-s-Modpacks/Stacia-2-Expert#9]
after having built the oil tank multiblock I accidentally grabbed the multiblock itself with carry On shift+R-click, placed it back down and broke the invisible block to spawn the whole structure, then proceeded to "fix" the broken multiblock simply by breaking one block and plaing it back.
it can subsequently be used to dupe evrey possible immersive contruction material being used from IP

https://clips.twitch.tv/GorgeousUgliestBubbleteaPJSugar-ulukR_DKaPvZNi1a

tested (and works) with oil tank and coker for now

likely fixable trough carry-on config

**Comment by Zulussuu** [comment]
Fixed
